### PR TITLE
Fixed not to use magic numbers

### PR DESCRIPTION
**Pull request by Korilakkuma**
I think that it is better to use the sample-rate of `AudioBuffer`.

### CODE REVIEW

**Comment by akihikodaki** [comment]
Good insight. Thank you for your contribution.
Indeed this works fine and would save time for audio sources with low resolution. However I have some reasons that I cannot accept your pull request. Please let me now if they are convincing for you.

# Consistency with runtime playbacks

The hardcoded number, 44,100 is not arbitrary. The number is expected to be equal to most configurations for runtime playbacks. That makes the result of `getFloatFrequencyData`, which this entire library relies on, consistent.
See [Web Audio API specification](https://webaudio.github.io/web-audio-api/) for the behavior of `getFloatFrequencyData`. tl;dr: the lower the resolution of the audio context is, the lower the resolution of `getFloatFrequencyData` will also be.

The consistency of the result matters because an application using this dependency, [Pawoo Music](https://music.pawoo.net/) provides runtime editing feature. It would surprise users that offline rendering results different.

Though this is off-topic, I think `OfflineAudioContext` and its `pause` method should be provided on browsers with `AnalyserNode`. It helps to get consistent results on any environments by specifying consistent sample rate.

By the way, I found the code is not so kind that it does not explain the hardcoded number thanks to this pull request. I will fix it later.

# Low resolution requirement

If we could set arbitrary sample rate, I would let it always use a low sample rate (actually I used 22,050 while early development.) The resolution requirement for visualization is low anyway.

You would need a parameter to provide sample rate from your application if it uses this library and you want to reduce its cost. You can take advantage of it by giving a small number. An issue or a pull request for such a feature will be welcomed if you want.

**Comment by Korilakkuma** [comment]
Thank you for the detailed comment. I accepted it. So, I made a correction to make the magic number meaningful.

**Comment by akihikodaki** [comment]
Sorry if my previous comment was confusing, but I did not meant what 44,100 stands for is unclear. It is obviously sample rate. The question we must deal with here is why the sample rate is 44,100.

**Comment by akihikodaki** [comment]
I added a comment regarding the sample rate with commit ce207575d212d621c2c0bccac23cf0091d84cb46.
It is notable that the comment also mentions the number of channels, which did not have any explanation, either.

I'll close this issue in favor of the commit. Thank you for your contribution again.

**Pull request closed without merging**
